# Generated by Django 4.0.3 on 2022-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskallocadmin',
            name='username',
            field=models.TextField(max_length=20),
        ),
    ]
