# Generated by Django 4.0.3 on 2022-04-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0003_alter_taskallocadmin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('task', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='taskAllocadmin',
        ),
    ]
