# Generated by Django 4.0.3 on 2022-04-19 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timescale', '0004_taskalloc_delete_taskallocadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskalloc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL),
        ),
    ]
