# Generated by Django 4.0.3 on 2022-05-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0013_alter_shiftdept_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskalloca',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timescale.shiftdept'),
        ),
    ]
