# Generated by Django 4.0.3 on 2022-05-21 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timescale', '0014_alter_taskalloca_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dept', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('username', models.CharField(max_length=20)),
                ('task', models.TextField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='taskAllocA',
        ),
    ]
