# Generated by Django 4.0.3 on 2022-05-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0016_taskalloca_delete_taskalloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taskAllocA',
        ),
    ]
