# Generated by Django 4.0.3 on 2022-05-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0018_taskalloca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskalloca',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='timescale.shiftdept'),
        ),
        migrations.AlterField(
            model_name='taskalloca',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shit', to='timescale.shiftdept'),
        ),
    ]
