# Generated by Django 4.0.3 on 2022-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0019_alter_taskalloca_dept_alter_taskalloca_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskalloca',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='taskalloca',
            name='shift',
        ),
    ]
